baseurl = "http://blog.jongbin.com/"
title = "1024"
copyright = "&copy; 2016 Jongbin Jung"
languageCode = "ko-KR"
paginate = 5
theme = "base16"

# Enable comments by entering your Disqus shortname
disqusShortname = "jongbin"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""
