baseurl = "https://blog.jongbin.com/"
title = "1024"
copyright = "&copy; 2016 Jongbin Jung"
paginate = 10
# theme = "base16"
theme = "paper"

# Language settings
languageCode = "ko-KR"
hasCJKLanguage = true

# Enable codefence highlighting
PygmentsCodeFences = true

# Enable comments by entering your Disqus shortname
disqusShortname = "jongbin"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-88094548-1"

FootnoteReturnLinkContents = "↩"

[params]
  author = "정종빈"
  github = "https://github.com/jongbinjung"
  iconTitles = ["Github"]

[permalinks]
  post = "/:year/:month/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
