---
title: "통계적으로 유의미한 개소리"
description: "통계적으로 유의미한 개소리 같은 결과들에 대한 무의미한 생각"
tags: ["R", "연구", "과학", "파워포즈", "개소리탐방"]
categories:  ["분석"]
author: "정종빈"
date:  "2017-03-13T16:25:03-08:00"

draft: true
mathjax: false
disqus: true

slug: "mister-p"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 개소리에서 과학까지

최근(이라고 하기에는 이제 첫 논문이 나온지 6년도 더 된 것 같지만) 
[자신감 넘치는 포즈를 취하면 실제로 자신감이 
생긴다](http://news.chosun.com/misaeng/site/data/html_dir/2016/02/04/2016020403851.html)던가
[여성은 배란기에 소비 성향이 더 커진다](https://1boon.kakao.com/dbr/72)는
맥락의, 얼핏 듣기에도 개소리 같은 이야기들이, "과학적 연구 결과"라며 등장하는 
일이 넘쳐난다.
정신 차리고 들어보면, 초딩이 듣기에도 어이 없을 주장임에도 불구하고, 
잘 알려지고 신뢰가 가는 미디어(TED 토크, 혹은 위 링크의 경우 조신일보와 동아 
비즈니스 리뷰)를 통해, "과학적"이라는 타이틀, 그리고 "있어 보이는 긴 영어 이름의 
저널에 실린 논문"을 동반하면서, 이런 상식을 뒤엎는 개소리는 어느새 
"놀라운 인사이트!"가 되어 사회를 --- 그리고 어쩌면 (경영)학계를? --- 흔들어 
놓는다.
심지어, 그 연구들을 진행한 팀들이 보통 하버드 같은 유명한 대학 교수들이 이끄는 
팀들이라 하니, 그 결과에 신뢰가 가지 않을 수 없다. 

## 상식

복잡(해 보일 수 있지만 조금만 읽어보면 사실 아주 단순)한 "과학적 근거"의 계산
등을 이야기 하기에 앞서, 상식적으로 생각해보자. "자신감 넘치는 포즈를 취하면 
자신감이 생긴다"는 연구에서의 실험 내용을 보면

> 실험자를 두 그룹으로 나눠 첫 번째 그룹은 다리와 두 팔을 최대한 뻗는 [자신감 
> 넘치는 포즈]를 취하게 했다. 
> 두 번째 그룹은 팔짱을 끼거나 책상에 턱을 괴고 아래를 보게 하는 [자신감 낮은 
> 포즈]를 잡도록 주문했다. 
>
> 2분 뒤 참가자들의 타액을 채취해 분석했더니 [자신감 넘치는 포즈]를 취한 그룹은
> 기억력과 자신감을 높여주는 호르몬인 테스토스테론이 20% 증가했다.
> 반면 만성 피로와 두통, 불안감을 유발하는 코르티솔이 25% 감소했다.
> [자신감 낮은 포즈]를 취한 그룹은 코르티솔이 15% 증가하고,
> 테스토스테론은 10% 감소했다.
>
> 이어 두 그룹이 모의 면접을 보게 했다.
> 그 결과 파워 포즈 자세를 한 사람들이 면접에 통과할 확률이 20% 이상 높았다.

...는 것이다. "다리와 두 팔을 최대한 뻗는" 자세를 2분간 취하면, 테스토스테론이 
20% 증가하고, 이 테스토스테론의 증가와 코르티솔의 감소가 면접에 통과할 확률을 
20% 이상 높여 줬다는 건데 ... 우선, [테스토스테론 보충제를 판매하는 사이트](https://www.bodybuilding.com/fun/do-testosterone-boosters-really-work.html)의
홍보 문구에 의하면, 12일간 테스토스테론 보충제를 꾸준히 복용했을 때, 약 42% 
증가를 기대할 수 있다고 한다.


## "과학적 근거"의 한계

미디어에서 "과학적 근거"가 있다고 할 때는 보통 "(유명한) 저널에 논문이 개제 
되었다"를 의미하고, (적어도 사회과학계에서) "저널에 논문이 개제 되었다"는 것은
보통 "통계적으로 유의미한 결과를 찾았다"는 의미로 해석 할 수 있다.

잠깐 고등학교 수학(확률통계) 시간으로 돌아가서 "통계적으로 유의미하다"는 것이
무슨 의미인지 돌이켜 보자. 우선, 두 개의 대립하는 가설을 생각해 보자:

- 가설0: 자신감 넘치는 포즈는 실제 자신감에 영향을 **주지 않는다**
- 가설1: 자신감 넘치는 포즈는 실제 자신감에 영향을 **준다**

이 두 개의 가설을 검증하기 위해서는, 과학적인 실험을 계획해 볼 수 있다. 즉, 
실험자를 두 그룹으로 나눠서 한 그룹은 자신감 넘치는 포즈를 취하게 하고, 다른 
그룹은 자신감이 넘치는 포즈를 취하지 않게 한 후, 두 그룹의 실제 자신감에 어떤 
변화가 있었는지 측정해서 비교해 볼 수 있다[^1].
그런데, 아무리 실험을 잘 계획해서 진행하더라도, 세상에는 연구자가 마음대로 할
수 없는 요소들이 많기 때문에, 그 결과는 매번 조금씩 다르게 된다. 예를 들어, 
앞/뒷면이 나올 확률이 정확히 50%씩인 동전을 만들어서 100번을 던지더라도 정확하게 
50번만 앞면이 나오지 않듯, 실제로 위 가설 중 가설0이 사실임에도 불구하고, 단순히 
우연의 일치로 마치 가설1이 사실인 것 같은 실험 결과가 나올 수도 있다는 것이다.
이러한 "우연의 일치"로 인한 잘못된 결론을 감안해서, 통계에서는 
p값(p-value)이라는 것을 사용하는데, p값의 의미는 쉽게 말해

> 가설0이 사실이라고 가정했을 때, 지금의 실험 결과에서 본 것 만큼이나 큰 차이가
> 나올 확률

... 이다. 다시, 동전을 던지는 실험을 생각해보면,

- 가설0: 동전의 앞/뒷면이 나올 확률은 정확히 50:50이다
- 가설1: 동전의 앞/뒷면이 나올 확률은 정확히 50:50이 아니다

고 했을 때, 100번 중 51번 앞면이 나왔다면, 가설0이 사실이라고 했을 때 이런 
결과가 나올 확률은 꽤 크기 때문에 이 실험의 p값은 상당히 높을 것이다. 반면, 
100번 중 99번 앞면이 나왔다면, 가설0이 사실이라고 했을 때 이런 결과(99번의 
앞면)가 나올 확률은 몹시 적고, 따라서 p값도 적다고 할 수 있다.

일반적으로 "과학적 저널"에서 "통계적으로 유의미한 결과"라고 할 때, 이 p값이 0.05 
보다 적음을 이야기 한다.


[^1]: 정확히 따지자면, 훨씬 조심스럽게 따지고 고민해 봐야할 문제들이 많지만, 이해를 돕기 위해 일단은 이정도로 해두자.

